### ISSUE TITLE
Skew functionality still in tutorial paper and OSF materials/code

### ISSUE THREAD

**Issue by statisfactions** [dbaranger/InteractionPoweR#4]
The PsyArXiv tuorial, OSF supplementary material, and OSF R code all still contain references to the ability to simulate varying skew and/or the defunct `skew.x1` and `skew.x2` variables.

I recognize this is not really a bug with the package as is, since I see that you [deliberately removed](https://github.com/dbaranger/InteractionPoweR/commit/e4f7fd7d3a546f58afd0f4cef41f197232c8bc3b) this functionality. It took me a little while to figure out what was going on, so I'm just adding this issue for your and other's reference.

One option would be to deprecate the options with a warning in case others are trying to use this code.

**Comment by dbaranger** [comment]
Hi! Sorry this happened. We are in the middle of responding to reviews, so some things are not in sync (the manuscript is still being edited). I appreciate the suggestion of adding the deprecate errors. I'll look into adding that to the next release.
Thanks for using the software!
David

**Comment by statisfactions** [comment]
Good luck with the review process, and thank you for the (much-needed)
software!

Ethan

**Comment by dbaranger** [comment]
The latest version now issues an informative error if the user supplies a skew.
