### ISSUE TITLE
Plot Power of Interaction Effect as Function of the Effect Size 

### ISSUE THREAD

**Issue by SvenjaFriess** [dbaranger/InteractionPoweR#6]
Hello. 

Many thanks for sharing this very cool package. As I am not really familiar with R, I'm wondering if and how it is possible to simulate the power of an interaction effect between x1 & x2 if both independent variables are BINARy using the "power_interaction"-function to create a plot that shows the power (y-axis) as the function of potential detectable effect sizes (x-axis)?

Many thanks in advance and kind regard.s

**Comment by dbaranger** [comment]
Hi, yes this is very doable, for example:

```
power_test = power_interaction_r2(
                  alpha = 0.05,                  # p-value
                  N = 350                ,       # sample size
                  r.x1.y = .2,                   # correlation between x1 and y
                  r.x2.y =  .1,                  # correlation between x2 and y
                  r.x1.x2 = .2,                  # correlation between x1 and x2
                  k.x1 = 2,                       # x1 is binary
                  k.x2 = 2,                       # x2 is binary
                  r.x1x2.y = seq(.1,.2,by=.005))  # correlation between x1x2 and y
                  
power_test
```

Or you can use our web app: https://mfinsaas.shinyapps.io/InteractionPoweR/?_inputs_&inTabset=%22Instructions%22&run=0&detailed=false&k.y.levels=null&r.x1.y=%22.1%22&k.x1=%22binary%22&r.x1x2.y=%22.1%2C.2%2C.3%2C.4%22&cl=1&N=%22300%22&n.iter=1000&r.x1.x2=%220%22&rel.x1=%221%22&rel.y=%221%22&pwr.target=0.8&seed=0&k.x1.levels=null&k.x2=%22binary%22&r.x2.y=%22.1%22&Alpha=0.05&k.y=%22continuous%22&adjust.correlations=true&k.x2.levels=null&rel.x2=%221%22
